fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: contact@moncpf.info
        sender_name: inscription
    registration:
        form:
           type: App\Form\RegistrationType
        confirmation:
           enabled: true