swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    #encryption: '%mailer_encryption%'
