vich_uploader:
    db_driver: orm

    mappings:
        file_pdf:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/public/files'
        file_pdf2:
            uri_prefix: /files2
            upload_destination: '%kernel.project_dir%/public/files2'
        file_pdf3:
            uri_prefix: /files3
            upload_destination: '%kernel.project_dir%/public/files3'