<?php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      max = 40,
     *      minMessage = "Votre nom doit contenir minimum {{ limit }} caractère",
     *      maxMessage = "Votre nom ne doit pas dépasser {{ limit }} caractère"
     * )
     */
    protected $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      max = 40,
     *      minMessage = "Votre prénom doit contenir minimum {{ limit }} caractère",
     *      maxMessage = "Votre prénom ne doit pas dépasser {{ limit }} caractère"
     * )
     */
    protected $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *      pattern = "/^0[1-78]([-. ]?[0-9]{2}){4}$/",
     *      message = "Votre numéro {{ value }} n'est pas valide !"
     * )
     */
    protected $numeroDeTelephone;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumeroDeTelephone(): ?string
    {
        return $this->numeroDeTelephone;
    }

    public function setNumeroDeTelephone(string $numeroDeTelephone): self
    {
        $this->numeroDeTelephone = $numeroDeTelephone;

        return $this;
    }

    public function setEmail($email)
    {
        $this->setUsername($email);

        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }
}